Multi-select component
rx/presenters pull request #301
Opened 2021-03-11 14:56 UTC by dsgraham

Adds a new component that behaves like a select list, but is composed of a checkbox group.

2021-03-11 22:52 UTC, rx requested changes
Demo error: http://localhost:9292/multi_selects
```
NoMethodError at /multi_selects
undefined method `checkbox' for #<Voom::Presenters::DSL::Components::Select::Option:0x00007f93461b5388>
file: multi_select.erb location: block in __tilt_70135244506840 line: 18

BACKTRACE
(expand)

JUMP TO: GET POST COOKIES ENV
/Users/russelledens/dev/rx/presenters/views/mdc/components/multi_select.erb in block in __tilt_70135244506840
        <%= erb :"components/checkbox", :locals => {comp: option.checkbox, class_name: 'v-multi-select--option'} %>
/Users/russelledens/dev/rx/presenters/views/mdc/components/multi_select.erb in each
      <% comp.options.each do |option| %>
/Users/russelledens/dev/rx/presenters/views/mdc/components/multi_select.erb in __tilt_70135244506840
      <% comp.options.each do |option| %>
```

2021-03-11 22:52 UTC, rx commented on lib/voom/presenters/dsl/components/multi_select.rb
> +            def _selected?
Any reason this has the `_` on the method name?

2021-03-11 22:52 UTC, rx commented on views/mdc/assets/js/components/multi-select.js
> +    // this.setMutationHandler();
```suggestion
```

2021-03-11 22:52 UTC, rx commented on views/mdc/assets/js/components/multi-select.js
> +  // Attempt to re-render when a hidden component becomes visible
Same as above ... remove commented out code.

2021-03-11 22:52 UTC, rx commented on views/mdc/components/multi_select.erb
> +<% end %>
```suggestion
<% end %>

```

2021-03-12 16:40 UTC, dsgraham commented on lib/voom/presenters/dsl/components/multi_select.rb
> +            def _selected?
That just got copied over from the Select::Option class. Neither of them appear to be used anywhere, so I'll look into removing them.

2021-03-12 21:34 UTC, rx approved these changes

2021-03-12 21:38 UTC, rx requested changes
Seeing a CSS issue in the demo:
![Image of CS Issue with Multi Selects](https://dl.dropbox.com/s/7zzi19801s7j764/Screen%20Shot%202021-03-12%20at%204.35.56%20PM.png?dl=0)

2021-03-15 12:47 UTC, dsgraham commented
> Seeing a CSS issue in the demo:

Yeah, I'm still working on that one.

2021-03-17 13:53 UTC, rx approved these changes

2021-03-17 13:53 UTC, merged